###
POST http://localhost:3000/api/user http/1.1
Content-Type: application/json

{
    "nickname":"Vertrack",
    "email":"vertrack@hotmail.com"
}


###
GET  http://localhost:3000/api/user http/1.1
Content-Type: application/json


###
GET  http://localhost:3000/api/user/63256fae3750b6f118de986b http/1.1
Content-Type: application/json


###
PUT  http://localhost:3000/api/user/63252de30fc7e01259edcf7a http/1.1
Content-Type: application/json

{
    "nickname":"arzeusy",
    "email":"arzeusy@hotmail.com"
}


###
POST http://localhost:3000/api/user/signup http/1.1
Content-Type: application/json

{
    "nickname":"admin",
    "email":"admin@gmail.com",
    "password":"12345",
    "confirmPassword":"12345"
}

###
POST http://localhost:3000/api/user/signin http/1.1
Content-Type: application/json

{
    "email":"paqui@gmail.om",
    "password":"12345"
}

###
GET http://localhost:3000/api/trivia/answers/632d560c87957b2f5d8081d3 http/1.1
Content-Type: application/json


###
GET http://localhost:3000/api/trivia/onGame http/1.1
Content-Type: application/json

{
    "Episode":[1, 2]
}


###
POST  http://localhost:3000/api/trivia/savePoints/632f280e7e5b4ea11c430639 http/1.1
Content-Type: application/json

{
    "points":1
}





###
POST  http://localhost:3000/api/user/rank http/1.1
Content-Type: application/json

